# Reference: https://www.exclamationlabs.com/blog/continuous-deployment-to-npm-using-gitlab-ci/

# GitLab uses docker in the background, so we need to specify the
# image versions. This is useful because we're freely to use
# multiple node versions to work with it. They come from the docker
# repo.
# Uses NodeJS V 9.4.0
image: node:20.11.1

# You specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
  - build

Build:
  stage: build
  tags:
    - node
  before_script:
    - npm install
  script:
    - npm run build
