image: node:20.11.1

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli@17.0.9
    - npm install
    - ng build
    - mkdir -p public
    - mv dist/redesign/browser/* public/
  artifacts:
    paths:
      - public
  only:
    - main
    - master
    - pages
